# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Den Williams
tagline:          'Tech enthusiast, developer, CTO'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://denwilliams.net
baseurl:          /

author:
  name:           'Den Williams'
  url:            http://denwilliams.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
